-- =============================================================================
--  DRONE AIRSPACE ZONING PLATFORM — DATABASE SCHEMA (MVP, Region 4 pilot)
-- =============================================================================
--  Target: PostgreSQL 15+ with PostGIS. Written for Supabase; portable to
--          Neon and Railway unchanged (all standard Postgres + PostGIS).
--
--  DESIGN COMMITMENTS ENCODED HERE (settled in planning):
--    * Two-stage logic: hard CONSTRAINTS first, then weighted SUITABILITY.
--    * SIX AHP-weighted factors (matches Drone-2 §3.4.1 methodology).
--    * THREE-LEVEL scoring hierarchy:
--         L1 Factor    -> carries the AHP weight            (mcda_factors)
--         L2 Sub-type  -> default 1-5 score / buffer / zone (mcda_subtypes)
--         L3 Feature   -> per-feature attribute override     (mcda_feature_rules)
--      Cascade: L3 override -> else L2 default. Weight (L1) always applies.
--    * 4-tier zoning: PROHIBITED / RESTRICTED / CONDITIONAL / SUITABLE.
--    * Precedence: MOST-RESTRICTIVE-WINS (both for constraint overlap and for
--      multiple sub-types touching one cell -> take MAX score).
--    * H3 hexagon grid, resolution 9 (per-cell reason retention).
--    * CRS: store 4326, BUFFER in UTM 21N (EPSG:32621), serve 3857/4326.
--    * Weights are RENORMALISED AT RUN TIME (weight_i / sum(weights)), so any
--      positive weights run without breaking — this is what lets you tweak
--      weights / do +/-10% sensitivity analysis without the program failing.
--    * Every input layer carries a CONFIDENCE tag for the location report.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 0. EXTENSIONS
-- -----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS postgis;
-- H3 extensions are OPTIONAL. On Supabase they exist and enable in-database hex
-- generation; elsewhere (Neon, Railway, vanilla Postgres) the Python `h3` library
-- in ingest.py generates the grid instead. Schema stores h3_index as TEXT + geom
-- either way, so nothing downstream depends on the extension.
DO $$ BEGIN
    CREATE EXTENSION IF NOT EXISTS h3;
    CREATE EXTENSION IF NOT EXISTS h3_postgis;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'h3 extensions unavailable — grid will be generated by ingest.py (fine).';
END $$;


-- -----------------------------------------------------------------------------
-- 1. ENUMS / TYPES
-- -----------------------------------------------------------------------------
-- Zone order encodes severity (most severe first). Used for most-restrictive-wins.
CREATE TYPE drone_zone AS ENUM (
    'PROHIBITED',   -- No-fly. Hard constraint.
    'RESTRICTED',   -- Authorization required.
    'CONDITIONAL',  -- Caution / mitigation.
    'SUITABLE'      -- Lower-risk, normal rules.
);

-- How a sub-type participates in the model.
CREATE TYPE mcda_treatment AS ENUM (
    'constraint',   -- Hard rule: buffer -> locked output zone.
    'factor'        -- Weighted suitability: contributes a 1-5 score.
);

-- Data trustworthiness, surfaced in the location report.
CREATE TYPE data_confidence AS ENUM (
    'verified',     -- From a named authoritative agency (e.g. Bureau of Statistics).
    'open_data',    -- Reputable open dataset (e.g. Protected Planet).
    'proxy_osm',    -- OpenStreetMap / crowd-sourced fill.
    'digitized',    -- Hand-digitized / interpretive (e.g. some GuyNode layers).
    'unverified'    -- Placeholder / incomplete; treat as provisional.
);


-- shared updated_at trigger
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- =============================================================================
--  CONFIGURATION / RULES ENGINE  (the "logic stored separately from data")
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 2. LEVEL 1 — FACTORS (carry the AHP weight)
-- -----------------------------------------------------------------------------
CREATE TABLE mcda_factors (
    factor_id      SERIAL PRIMARY KEY,
    factor_key     TEXT UNIQUE NOT NULL,       -- stable machine key
    factor_name    TEXT NOT NULL,
    description    TEXT,
    weight         NUMERIC(6,4) NOT NULL DEFAULT 0,   -- RAW weight; renormalised at run time
    weight_source  TEXT,                        -- provenance of the weight value
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT weight_non_negative CHECK (weight >= 0)
);
CREATE TRIGGER trg_factors_updated BEFORE UPDATE ON mcda_factors
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON COLUMN mcda_factors.weight IS
    'Raw AHP weight. The engine renormalises (weight/SUM(active weights)) at run '
    'time, so weights need NOT sum to 1.0 in storage. This makes weight edits and '
    '+/-10% sensitivity perturbations safe — any non-negative set runs.';

-- Seed: SIX factors, EQUAL provisional weights (pending AHP elicitation).
INSERT INTO mcda_factors (factor_key, factor_name, description, weight, weight_source) VALUES
 ('population',              'Population Density',                         'Ground-risk exposure from people on the ground.',                     0.1667, 'provisional — equal weighting pending AHP'),
 ('land_use',               'Land Use / Land Cover',                      'Operational environment (urban, industrial, agricultural, forest, water).', 0.1667, 'provisional — equal weighting pending AHP'),
 ('infrastructure_sensitive','Critical Infrastructure & Sensitive Locations','Bridges, ports, power AND schools, hospitals (single factor per methodology §3.4.1).', 0.1667, 'provisional — equal weighting pending AHP'),
 ('environmental',          'Environmental Sensitivity',                  'Protected areas, wetlands, mangroves, wildlife habitat.',             0.1667, 'provisional — equal weighting pending AHP'),
 ('airspace_activity',      'Airspace Activity & Aviation Considerations','Non-constraint aviation risk: airspace class, activity levels.',      0.1667, 'provisional — equal weighting pending AHP'),
 ('regulatory',             'Regulatory Considerations',                  'Local bylaws / municipal drone rules where mapped.',                  0.1667, 'provisional — equal weighting pending AHP');


-- -----------------------------------------------------------------------------
-- 3. DATA REGISTRY — physical spatial input tables + provenance/confidence
-- -----------------------------------------------------------------------------
CREATE TABLE mcda_layers (
    layer_id     SERIAL PRIMARY KEY,
    layer_key    TEXT UNIQUE NOT NULL,          -- e.g. 'osm_health_facilities'
    table_name   TEXT NOT NULL,                 -- logical source name; all geometries physically live in mcda_features (see 6b)
    geom_type    TEXT NOT NULL,                 -- 'point' | 'line' | 'polygon'
    factor_id    INTEGER REFERENCES mcda_factors(factor_id),  -- suitability factor fed (NULL for pure constraint layers)
    source       TEXT,                          -- e.g. 'GuyNode / Bureau of Statistics'
    confidence   data_confidence NOT NULL DEFAULT 'unverified',
    license_note TEXT,                          -- redistribution / usage caveats
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_layers_updated BEFORE UPDATE ON mcda_layers
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Seed: the layers we sourced. Confidence reflects the earlier data audit.
INSERT INTO mcda_layers (layer_key, table_name, geom_type, factor_id, source, confidence, license_note) VALUES
 ('region4_boundary',       'mcda_region_boundary',    'polygon', NULL,
    'User shapefile (reprojected from EPSG:3857)', 'digitized', 'Study-area boundary; not a scored layer.'),
 ('guynode_population_ndc',  'src_population_ndc',      'polygon', (SELECT factor_id FROM mcda_factors WHERE factor_key='population'),
    'GuyNode / Bureau of Statistics (NDC-level)', 'verified', NULL),
 ('guynode_landcover',       'src_landcover',          'polygon', (SELECT factor_id FROM mcda_factors WHERE factor_key='land_use'),
    'GuyNode National Land Cover', 'open_data', NULL),
 ('guynode_schools_r4',      'src_schools',            'point',   (SELECT factor_id FROM mcda_factors WHERE factor_key='infrastructure_sensitive'),
    'GuyNode / Ministry of Education 2019', 'verified', NULL),
 ('osm_health_facilities',   'src_health_facilities',  'point',   (SELECT factor_id FROM mcda_factors WHERE factor_key='infrastructure_sensitive'),
    'OpenStreetMap (Overpass)', 'proxy_osm', 'Crowd-sourced fill for missing hospital layer.'),
 ('guynode_infrastructure',  'src_infrastructure',     'point',   (SELECT factor_id FROM mcda_factors WHERE factor_key='infrastructure_sensitive'),
    'GuyNode (bridges/ports/power)', 'digitized', 'Region 4 kokers layer flagged incomplete upstream.'),
 ('guynode_protected_areas', 'src_protected_areas',    'polygon', (SELECT factor_id FROM mcda_factors WHERE factor_key='environmental'),
    'GuyNode / Protected Planet (WDPA)', 'open_data', NULL),
 ('guynode_airports',        'src_airports',           'point',   NULL,
    'GuyNode / OurAirports + HDX', 'open_data', 'Feeds the aerodrome-proximity CONSTRAINT.'),
 -- Gaps kept explicit and inactive until GCAA coordination:
 ('gcaa_restricted_airspace','src_restricted_airspace','polygon', NULL,
    'PENDING — GCAA coordination', 'unverified', 'No open substitute exists. Registered but inactive.'),
 ('gcaa_military_security',  'src_military_security',  'point',   NULL,
    'PENDING — GCAA / security agency', 'unverified', 'Deliberately NOT filled from OSM (safety-critical gap).');
-- Mark the two gap layers inactive until data exists.
UPDATE mcda_layers SET is_active = FALSE WHERE layer_key IN ('gcaa_restricted_airspace','gcaa_military_security');


-- -----------------------------------------------------------------------------
-- 4. LEVEL 2 — SUB-TYPES (default score / buffer / output zone per category)
-- -----------------------------------------------------------------------------
CREATE TABLE mcda_subtypes (
    subtype_id       SERIAL PRIMARY KEY,
    subtype_key      TEXT UNIQUE NOT NULL,       -- e.g. 'hospital', 'international_airport'
    subtype_name     TEXT NOT NULL,
    factor_id        INTEGER REFERENCES mcda_factors(factor_id),  -- required for treatment='factor'
    treatment        mcda_treatment NOT NULL,
    -- Factor (suitability) defaults:
    default_score    SMALLINT,                   -- 1..5, used when treatment='factor'
    -- Constraint defaults:
    default_buffer_m NUMERIC,                     -- metres; buffer computed in EPSG:32621
    default_zone     drone_zone,                  -- locked zone when treatment='constraint'
    reason_template  TEXT,                         -- human string for the location report
    score_source     TEXT,                         -- provenance / justification (thesis exhibit)
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT score_range CHECK (default_score IS NULL OR default_score BETWEEN 1 AND 5),
    CONSTRAINT factor_needs_factor_id CHECK (treatment <> 'factor' OR factor_id IS NOT NULL),
    CONSTRAINT constraint_needs_zone  CHECK (treatment <> 'constraint' OR default_zone IS NOT NULL)
);
CREATE TRIGGER trg_subtypes_updated BEFORE UPDATE ON mcda_subtypes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Seed — CONSTRAINT sub-types (buffers are PROVISIONAL, pending GCAA validation).
INSERT INTO mcda_subtypes (subtype_key, subtype_name, factor_id, treatment, default_buffer_m, default_zone, reason_template, score_source) VALUES
 ('aerodrome_proximity','Aerodrome / airport proximity', NULL, 'constraint', 5000, 'PROHIBITED',
    'Within {dist} m of {name} (aerodrome protection zone)', 'provisional — ICAO-adjacent aerodrome protection, pending GCAA'),
 ('heliport_proximity', 'Heliport proximity',            NULL, 'constraint', 1000, 'RESTRICTED',
    'Within {dist} m of heliport {name}', 'provisional — minimal approach protection, pending GCAA'),
 ('restricted_airspace','Restricted / controlled airspace', NULL, 'constraint', 0, 'PROHIBITED',
    'Inside restricted airspace {name}', 'PENDING — GCAA airspace polygons'),
 ('military_security',  'Military / security facility',  NULL, 'constraint', 2000, 'PROHIBITED',
    'Within {dist} m of security-sensitive site', 'PENDING — GCAA / security agency');

-- Seed — FACTOR sub-types.
-- infrastructure_sensitive (buffered point features; take MAX score where overlapping):
INSERT INTO mcda_subtypes (subtype_key, subtype_name, factor_id, treatment, default_score, default_buffer_m, reason_template, score_source) VALUES
 ('hospital', 'Hospital', (SELECT factor_id FROM mcda_factors WHERE factor_key='infrastructure_sensitive'), 'factor', 5, 300,
    'Within {dist} m of hospital {name}', 'standardised (paper unspecified) — highest sensitive-site score'),
 ('school',   'School',   (SELECT factor_id FROM mcda_factors WHERE factor_key='infrastructure_sensitive'), 'factor', 4, 200,
    'Within {dist} m of school {name}', 'standardised (paper unspecified)'),
 ('bridge',   'Bridge',   (SELECT factor_id FROM mcda_factors WHERE factor_key='infrastructure_sensitive'), 'factor', 3, 200,
    'Within {dist} m of bridge {name}', 'standardised (paper unspecified)'),
 ('port',     'Port',     (SELECT factor_id FROM mcda_factors WHERE factor_key='infrastructure_sensitive'), 'factor', 3, 400,
    'Within {dist} m of port {name}', 'standardised (paper unspecified)'),
 ('power',    'Power infrastructure', (SELECT factor_id FROM mcda_factors WHERE factor_key='infrastructure_sensitive'), 'factor', 3, 300,
    'Within {dist} m of power infrastructure', 'standardised (paper unspecified)');

-- land_use (polygon coverage, no buffer — cell inherits the class it sits in):
INSERT INTO mcda_subtypes (subtype_key, subtype_name, factor_id, treatment, default_score, reason_template, score_source) VALUES
 ('lu_urban',       'Urban / built-up', (SELECT factor_id FROM mcda_factors WHERE factor_key='land_use'), 'factor', 5, 'Urban / built-up land cover', 'standardised (paper unspecified)'),
 ('lu_industrial',  'Industrial',       (SELECT factor_id FROM mcda_factors WHERE factor_key='land_use'), 'factor', 4, 'Industrial land cover', 'standardised (paper unspecified)'),
 ('lu_forest',      'Forest',           (SELECT factor_id FROM mcda_factors WHERE factor_key='land_use'), 'factor', 3, 'Forest land cover', 'standardised (paper unspecified)'),
 ('lu_agriculture', 'Agriculture / open',(SELECT factor_id FROM mcda_factors WHERE factor_key='land_use'), 'factor', 2, 'Agricultural / open land', 'standardised — drone opportunity area'),
 ('lu_water',       'Water',            (SELECT factor_id FROM mcda_factors WHERE factor_key='land_use'), 'factor', 1, 'Water body', 'standardised (paper unspecified)');

-- population (areal join; banded scores live in Level 3 by density range):
INSERT INTO mcda_subtypes (subtype_key, subtype_name, factor_id, treatment, default_score, reason_template, score_source) VALUES
 ('population_density', 'Population density band', (SELECT factor_id FROM mcda_factors WHERE factor_key='population'), 'factor', 3,
    'Population density {value}/km^2', 'standardised — bands set from Region 4 distribution');

-- environmental (polygon overlay):
INSERT INTO mcda_subtypes (subtype_key, subtype_name, factor_id, treatment, default_score, reason_template, score_source) VALUES
 ('protected_area', 'Protected / environmentally sensitive area', (SELECT factor_id FROM mcda_factors WHERE factor_key='environmental'), 'factor', 4,
    'Inside protected area {name}', 'standardised (paper unspecified)');

-- airspace_activity & regulatory: sparse for Region 4 MVP — neutral default, low confidence.
INSERT INTO mcda_subtypes (subtype_key, subtype_name, factor_id, treatment, default_score, reason_template, score_source) VALUES
 ('airspace_class', 'Airspace class / activity', (SELECT factor_id FROM mcda_factors WHERE factor_key='airspace_activity'), 'factor', 2,
    'Airspace activity consideration', 'provisional — sparse data for Region 4'),
 ('local_bylaw',    'Local drone bylaw area',    (SELECT factor_id FROM mcda_factors WHERE factor_key='regulatory'), 'factor', 2,
    'Local regulatory consideration', 'provisional — sparse data for Region 4');


-- -----------------------------------------------------------------------------
-- 5. LEVEL 3 — FEATURE RULES (per-feature attribute overrides of L2 defaults)
--    Handles BOTH categorical refinements (size_class='large') and numeric
--    banding (population density value_min..value_max). Falls back to L2 when
--    no rule matches — this is the graceful cascade.
-- -----------------------------------------------------------------------------
CREATE TABLE mcda_feature_rules (
    feature_rule_id SERIAL PRIMARY KEY,
    subtype_id      INTEGER NOT NULL REFERENCES mcda_subtypes(subtype_id) ON DELETE CASCADE,
    match_attribute TEXT NOT NULL,               -- feature attribute inspected, e.g. 'size_class','density_per_km2','aerodrome_class'
    match_value     TEXT,                          -- categorical exact match (nullable)
    value_min       NUMERIC,                       -- numeric range low  (inclusive, nullable)
    value_max       NUMERIC,                       -- numeric range high (exclusive, nullable)
    -- Overrides (any NULL falls back to the sub-type default):
    score           SMALLINT,
    buffer_m        NUMERIC,
    output_zone     drone_zone,
    reason_template TEXT,
    source          TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT l3_score_range CHECK (score IS NULL OR score BETWEEN 1 AND 5),
    CONSTRAINT l3_match_present CHECK (match_value IS NOT NULL OR value_min IS NOT NULL OR value_max IS NOT NULL)
);
CREATE INDEX idx_feature_rules_subtype ON mcda_feature_rules(subtype_id);

-- Seed examples — the "big vs small" cases you described. Mostly LATENT for the
-- MVP (Region 4 data lacks these attributes) but present so national/richer data
-- activates them with no schema change.
-- Aerodrome size drives BOTH buffer and severity:
INSERT INTO mcda_feature_rules (subtype_id, match_attribute, match_value, buffer_m, output_zone, reason_template, source) VALUES
 ((SELECT subtype_id FROM mcda_subtypes WHERE subtype_key='aerodrome_proximity'), 'aerodrome_class', 'international', 5000, 'PROHIBITED', 'Within {dist} m of international airport {name}', 'provisional — pending GCAA'),
 ((SELECT subtype_id FROM mcda_subtypes WHERE subtype_key='aerodrome_proximity'), 'aerodrome_class', 'domestic',     3000, 'RESTRICTED', 'Within {dist} m of regional airport {name}',      'provisional — pending GCAA'),
 ((SELECT subtype_id FROM mcda_subtypes WHERE subtype_key='aerodrome_proximity'), 'aerodrome_class', 'airstrip',     1000, 'RESTRICTED', 'Within {dist} m of airstrip {name}',              'provisional — pending GCAA');
-- Hospital size drives score:
INSERT INTO mcda_feature_rules (subtype_id, match_attribute, match_value, score, buffer_m, reason_template, source) VALUES
 ((SELECT subtype_id FROM mcda_subtypes WHERE subtype_key='hospital'), 'size_class', 'large', 5, 400, 'Within {dist} m of major hospital {name}', 'standardised (latent — attribute rarely present in MVP data)'),
 ((SELECT subtype_id FROM mcda_subtypes WHERE subtype_key='hospital'), 'size_class', 'small', 4, 200, 'Within {dist} m of small hospital/clinic {name}', 'standardised (latent)');
-- Population density bands (ACTIVE for MVP — set from Region 4 distribution after load):
INSERT INTO mcda_feature_rules (subtype_id, match_attribute, value_min, value_max, score, reason_template, source) VALUES
 ((SELECT subtype_id FROM mcda_subtypes WHERE subtype_key='population_density'), 'density_per_km2',    0,   100, 1, 'Sparsely populated ({value}/km^2)',    'refit to Region 4 NDC 2012 distribution (range 0-3357/km^2)'),
 ((SELECT subtype_id FROM mcda_subtypes WHERE subtype_key='population_density'), 'density_per_km2',  100,   500, 2, 'Low density ({value}/km^2)',           'refit to Region 4 NDC 2012 distribution'),
 ((SELECT subtype_id FROM mcda_subtypes WHERE subtype_key='population_density'), 'density_per_km2',  500,  1500, 3, 'Moderate density ({value}/km^2)',      'refit to Region 4 NDC 2012 distribution'),
 ((SELECT subtype_id FROM mcda_subtypes WHERE subtype_key='population_density'), 'density_per_km2', 1500,  3000, 4, 'High density ({value}/km^2)',          'refit to Region 4 NDC 2012 distribution'),
 ((SELECT subtype_id FROM mcda_subtypes WHERE subtype_key='population_density'), 'density_per_km2', 3000, 1e9,   5, 'Very high density ({value}/km^2)',     'refit to Region 4 NDC 2012 distribution');


-- -----------------------------------------------------------------------------
-- 6. CLASSIFICATION THRESHOLDS (fully editable, like weights — API-exposed)
-- -----------------------------------------------------------------------------
CREATE TABLE mcda_zone_thresholds (
    zone        drone_zone PRIMARY KEY,
    score_min   NUMERIC,      -- inclusive lower bound on renormalised weighted score (NULL = constraint-driven)
    score_max   NUMERIC,      -- exclusive upper bound
    notes       TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_thresholds_updated BEFORE UPDATE ON mcda_zone_thresholds
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
COMMENT ON TABLE mcda_zone_thresholds IS
    'Editable via API (PATCH /config/thresholds). Model runs snapshot the '
    'thresholds in use (mcda_model_runs.params) so past runs stay reproducible.';
INSERT INTO mcda_zone_thresholds (zone, score_min, score_max, notes) VALUES
 ('PROHIBITED',  NULL, NULL, 'Assigned by hard constraint, not by score.'),
 ('RESTRICTED',  4.0,  5.01, 'High weighted risk OR a RESTRICTED constraint.'),
 ('CONDITIONAL', 2.5,  4.0,  'Moderate weighted risk.'),
 ('SUITABLE',    1.0,  2.5,  'Low weighted risk.');


-- =============================================================================
--  STUDY AREA, GRID, AND OUTPUTS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 6b. UNIFIED FEATURES TABLE (what ingestion writes; what the engine reads)
--     One table for all input features, tagged by layer + sub-type, with raw
--     attributes preserved in JSONB so Level-3 rules can match against them
--     (e.g. attrs->>'aerodrome_class', (attrs->>'density_per_km2')::numeric).
-- -----------------------------------------------------------------------------
CREATE TABLE mcda_features (
    feature_id  BIGSERIAL PRIMARY KEY,
    layer_id    INTEGER NOT NULL REFERENCES mcda_layers(layer_id),
    subtype_key TEXT NOT NULL REFERENCES mcda_subtypes(subtype_key),
    name        TEXT,
    attrs       JSONB NOT NULL DEFAULT '{}'::jsonb,
    geom        geometry(Geometry, 4326) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_features_geom    ON mcda_features USING GIST (geom);
CREATE INDEX idx_features_subtype ON mcda_features (subtype_key);
CREATE INDEX idx_features_layer   ON mcda_features (layer_id);

-- -----------------------------------------------------------------------------
-- 7. REGION BOUNDARY (store 4326; buffer math done in 32621 at run time)
-- -----------------------------------------------------------------------------
CREATE TABLE mcda_region_boundary (
    region_id   SERIAL PRIMARY KEY,
    region_key  TEXT UNIQUE NOT NULL,            -- e.g. 'region4_demerara_mahaica'
    region_name TEXT NOT NULL,
    geom        geometry(MultiPolygon, 4326) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_region_geom ON mcda_region_boundary USING GIST (geom);

-- -----------------------------------------------------------------------------
-- 8. H3 GRID (resolution 9 for Region 4). h3_index as TEXT for portability.
-- -----------------------------------------------------------------------------
CREATE TABLE mcda_grid (
    h3_index    TEXT PRIMARY KEY,               -- H3 cell index (string form)
    resolution  SMALLINT NOT NULL DEFAULT 9,
    region_id   INTEGER NOT NULL REFERENCES mcda_region_boundary(region_id),
    geom        geometry(Polygon, 4326) NOT NULL,
    centroid    geometry(Point, 4326),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_grid_geom     ON mcda_grid USING GIST (geom);
CREATE INDEX idx_grid_region   ON mcda_grid (region_id);

-- -----------------------------------------------------------------------------
-- 9. MODEL RUNS (versioning for reproducibility + sensitivity analysis)
--    Each run snapshots the weights actually used, so a run stays reproducible
--    even after weights are later edited in the UI.
-- -----------------------------------------------------------------------------
CREATE TABLE mcda_model_runs (
    run_id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    region_id        INTEGER NOT NULL REFERENCES mcda_region_boundary(region_id),
    h3_resolution    SMALLINT NOT NULL DEFAULT 9,
    weights_snapshot JSONB NOT NULL,             -- {factor_key: raw_weight} at run time
    params           JSONB,                       -- any other run parameters / scenario label
    label            TEXT,                        -- e.g. 'baseline', 'sensitivity: population +10%'
    status           TEXT NOT NULL DEFAULT 'pending',  -- pending | running | complete | failed
    created_by       TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at     TIMESTAMPTZ
);
CREATE INDEX idx_runs_region ON mcda_model_runs (region_id, created_at DESC);

-- -----------------------------------------------------------------------------
-- 10. CELL RESULTS (one row per hex per run). Carries the per-cell REASON data
--     that powers the click-based location report.
-- -----------------------------------------------------------------------------
CREATE TABLE mcda_cell_results (
    run_id            UUID NOT NULL REFERENCES mcda_model_runs(run_id) ON DELETE CASCADE,
    h3_index          TEXT NOT NULL REFERENCES mcda_grid(h3_index),
    final_zone        drone_zone NOT NULL,
    total_score       NUMERIC,                    -- renormalised weighted score (NULL if constraint-locked)
    factor_scores     JSONB,                      -- {factor_key: {score, weight, reasons[]}}
    constraint_reasons TEXT[],                    -- e.g. {'Within 5000 m of international airport CJIA'}
    dominant_reason   TEXT,                        -- the "main reason" for the report
    min_confidence    data_confidence,            -- lowest confidence among contributing layers
    PRIMARY KEY (run_id, h3_index)
);
CREATE INDEX idx_cell_results_zone ON mcda_cell_results (run_id, final_zone);

COMMENT ON TABLE mcda_cell_results IS
    'constraint_reasons + factor_scores together satisfy the methodology location '
    'report: zone, main reason, contributing factors, and data confidence per cell.';


-- =============================================================================
--  HELPERS
-- =============================================================================

-- Verification view: shows raw weights, the renormalised weights the engine will
-- actually use, and their sum. Because of run-time renormalisation, the raw sum
-- does NOT need to equal 1.0 — this view is a sanity aid, not a constraint.
CREATE VIEW mcda_weight_check AS
SELECT
    factor_key,
    factor_name,
    weight AS raw_weight,
    ROUND(weight / NULLIF(SUM(weight) FILTER (WHERE is_active) OVER (), 0), 4) AS normalised_weight,
    is_active
FROM mcda_factors
ORDER BY factor_key;

-- =============================================================================
--  NOTES FOR THE ENGINE (implemented in FastAPI, not in this DDL)
-- =============================================================================
--  SCORE RESOLUTION per (feature, cell):
--    1. If an active mcda_feature_rules row matches the feature's attribute
--       (categorical match_value OR numeric value_min<=v<value_max) -> use its
--       non-NULL overrides.
--    2. Else fall back to the sub-type (L2) defaults.
--    3. Multiple sub-types touching one cell within a factor -> MAX score
--       (most-restrictive-wins).
--  FACTOR AGGREGATION per cell:
--    total = SUM(factor_score_i * normalised_weight_i) over active factors,
--    where normalised_weight_i = raw_weight_i / SUM(active raw weights).
--    -> Renormalisation is why editing weights / +/-10% sensitivity never breaks.
--  CONSTRAINTS override suitability: any constraint hit locks final_zone by the
--    most-severe drone_zone among hits (enum order = severity).
--  BUFFERING: always ST_Transform(geom, 32621) before ST_Buffer(...), then back
--    to 4326 for storage/serving. Never buffer in 3857.
-- =============================================================================
