-- 016_seed_flag_presets.sql
-- Generated by scripts/generate_flag_preset_migration.py.
-- Seeds the canonical 45-country flag palette catalog without overwriting
-- created_at or touching unrelated/custom rule rows.

WITH desired_flags AS (
    SELECT value AS payload
    FROM jsonb_array_elements(
        $flag_presets$
[
  {
    "id": "antigua-and-barbuda",
    "name": "Antigua and Barbuda",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#CE1126",
        "feature_primary": "#0072C6",
        "feature_secondary": "#CAA712",
        "feature_minor": "#8F8239",
        "feature_headwater": "#E1CD79",
        "text_primary": "#111827",
        "text_secondary": "#CE1126"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FCD116",
        "feature_primary": "#0072C6",
        "feature_secondary": "#CE1126",
        "feature_minor": "#B45368",
        "feature_headwater": "#761123",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FCD116"
      }
    }
  },
  {
    "id": "argentina",
    "name": "Argentina",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#6392BE",
        "feature_primary": "#C5900B",
        "feature_secondary": "#A27709",
        "feature_minor": "#796834",
        "feature_headwater": "#CBB274",
        "text_primary": "#111827",
        "text_secondary": "#4F7598"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#F6B40E",
        "feature_primary": "#74ACDF",
        "feature_secondary": "#A3C8EA",
        "feature_minor": "#9CB7D4",
        "feature_headwater": "#5F758F",
        "text_primary": "#F8FAFC",
        "text_secondary": "#F6B40E"
      }
    }
  },
  {
    "id": "australia",
    "name": "Australia",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#00008B",
        "feature_primary": "#FF0000",
        "feature_secondary": "#A80000",
        "feature_minor": "#7C262F",
        "feature_headwater": "#CE716F",
        "text_primary": "#111827",
        "text_secondary": "#00008B"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FF0000",
        "feature_primary": "#4C4CAE",
        "feature_secondary": "#5757B2",
        "feature_minor": "#7279B5",
        "feature_headwater": "#353770",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FF0000"
      }
    }
  },
  {
    "id": "bahamas",
    "name": "Bahamas",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#00778B",
        "feature_primary": "#BF9521",
        "feature_secondary": "#A8831D",
        "feature_minor": "#7C6E3F",
        "feature_headwater": "#CEB97F",
        "text_primary": "#111827",
        "text_secondary": "#00778B"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FFC72C",
        "feature_primary": "#00778B",
        "feature_secondary": "#57A5B2",
        "feature_minor": "#72A4B5",
        "feature_headwater": "#356270",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FFC72C"
      }
    }
  },
  {
    "id": "barbados",
    "name": "Barbados",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#00267F",
        "feature_primary": "#BF951C",
        "feature_secondary": "#A88319",
        "feature_minor": "#7C6E3D",
        "feature_headwater": "#CEB97D",
        "text_primary": "#111827",
        "text_secondary": "#00267F"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FFC726",
        "feature_primary": "#335199",
        "feature_secondary": "#5770AB",
        "feature_minor": "#7287B1",
        "feature_headwater": "#35456C",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FFC726"
      }
    }
  },
  {
    "id": "belize",
    "name": "Belize",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#003F87",
        "feature_primary": "#CE1126",
        "feature_secondary": "#880B19",
        "feature_minor": "#6B2C3D",
        "feature_headwater": "#BD777D",
        "text_primary": "#111827",
        "text_secondary": "#003F87"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#CE1126",
        "feature_primary": "#265C99",
        "feature_secondary": "#5780B0",
        "feature_minor": "#7290B4",
        "feature_headwater": "#354E6F",
        "text_primary": "#F8FAFC",
        "text_secondary": "#DA4C5C"
      }
    }
  },
  {
    "id": "brazil",
    "name": "Brazil",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#002776",
        "feature_primary": "#009C3B",
        "feature_secondary": "#CCB200",
        "feature_minor": "#90882F",
        "feature_headwater": "#E2D36F",
        "text_primary": "#111827",
        "text_secondary": "#002776"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FFDF00",
        "feature_primary": "#009C3B",
        "feature_secondary": "#26478B",
        "feature_minor": "#58709F",
        "feature_headwater": "#1A2E5B",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FFDF00"
      }
    }
  },
  {
    "id": "canada",
    "name": "Canada",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#FF0000",
        "feature_primary": "#BD0000",
        "feature_secondary": "#7D0000",
        "feature_minor": "#65262F",
        "feature_headwater": "#B7716F",
        "text_primary": "#111827",
        "text_secondary": "#E60000"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FF0000",
        "feature_primary": "#FF4242",
        "feature_secondary": "#FF8282",
        "feature_minor": "#CF919A",
        "feature_headwater": "#914F56",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FF0000"
      }
    }
  },
  {
    "id": "china",
    "name": "China",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#DE2910",
        "feature_primary": "#B29B00",
        "feature_secondary": "#A89300",
        "feature_minor": "#7C772F",
        "feature_headwater": "#CEC26F",
        "text_primary": "#111827",
        "text_secondary": "#DE2910"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FFDE00",
        "feature_primary": "#DE2910",
        "feature_secondary": "#E97261",
        "feature_minor": "#C38888",
        "feature_headwater": "#854644",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FFDE00"
      }
    }
  },
  {
    "id": "costa-rica",
    "name": "Costa Rica",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#002B7F",
        "feature_primary": "#CE1126",
        "feature_secondary": "#880B19",
        "feature_minor": "#6B2C3D",
        "feature_headwater": "#BD777D",
        "text_primary": "#111827",
        "text_secondary": "#002B7F"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#CE1126",
        "feature_primary": "#335599",
        "feature_secondary": "#5773AB",
        "feature_minor": "#7289B1",
        "feature_headwater": "#35466C",
        "text_primary": "#F8FAFC",
        "text_secondary": "#DA4C5C"
      }
    }
  },
  {
    "id": "cuba",
    "name": "Cuba",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#002A8F",
        "feature_primary": "#CF142B",
        "feature_secondary": "#890D1C",
        "feature_minor": "#6B2D3F",
        "feature_headwater": "#BD787F",
        "text_primary": "#111827",
        "text_secondary": "#002A8F"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#CF142B",
        "feature_primary": "#3355A5",
        "feature_secondary": "#5772B5",
        "feature_minor": "#7288B6",
        "feature_headwater": "#354672",
        "text_primary": "#F8FAFC",
        "text_secondary": "#DB4F60"
      }
    }
  },
  {
    "id": "dominica",
    "name": "Dominica",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#006B3F",
        "feature_primary": "#D41C30",
        "feature_secondary": "#CAA712",
        "feature_minor": "#8F8239",
        "feature_headwater": "#E1CD79",
        "text_primary": "#111827",
        "text_secondary": "#006B3F"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FCD116",
        "feature_primary": "#D41C30",
        "feature_secondary": "#006B3F",
        "feature_minor": "#438475",
        "feature_headwater": "#054231",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FCD116"
      }
    }
  },
  {
    "id": "dominican-republic",
    "name": "Dominican Republic",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#002D62",
        "feature_primary": "#CE1126",
        "feature_secondary": "#880B19",
        "feature_minor": "#6B2C3D",
        "feature_headwater": "#BD777D",
        "text_primary": "#111827",
        "text_secondary": "#002D62"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#CE1126",
        "feature_primary": "#335781",
        "feature_secondary": "#577497",
        "feature_minor": "#7289A6",
        "feature_headwater": "#354761",
        "text_primary": "#F8FAFC",
        "text_secondary": "#DA4C5C"
      }
    }
  },
  {
    "id": "ecuador",
    "name": "Ecuador",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#034EA2",
        "feature_primary": "#EF3340",
        "feature_secondary": "#CCA700",
        "feature_minor": "#90822F",
        "feature_headwater": "#E2CD6F",
        "text_primary": "#111827",
        "text_secondary": "#034EA2"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FFD100",
        "feature_primary": "#EF3340",
        "feature_secondary": "#034EA2",
        "feature_minor": "#4474AC",
        "feature_headwater": "#073268",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FFD100"
      }
    }
  },
  {
    "id": "el-salvador",
    "name": "El Salvador",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#0047AB",
        "feature_primary": "#AE960F",
        "feature_secondary": "#A48D0F",
        "feature_minor": "#7A7438",
        "feature_headwater": "#CCBE77",
        "text_primary": "#111827",
        "text_secondary": "#0047AB"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#F9D616",
        "feature_primary": "#0D50AF",
        "feature_secondary": "#5786C8",
        "feature_minor": "#7293C1",
        "feature_headwater": "#35517C",
        "text_primary": "#F8FAFC",
        "text_secondary": "#F9D616"
      }
    }
  },
  {
    "id": "france",
    "name": "France",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#0055A4",
        "feature_primary": "#EF4135",
        "feature_secondary": "#9E2B23",
        "feature_minor": "#773E42",
        "feature_headwater": "#C98982",
        "text_primary": "#111827",
        "text_secondary": "#0055A4"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#EF4135",
        "feature_primary": "#0055A4",
        "feature_secondary": "#578FC3",
        "feature_minor": "#7298BE",
        "feature_headwater": "#35567A",
        "text_primary": "#F8FAFC",
        "text_secondary": "#EF4135"
      }
    }
  },
  {
    "id": "french-guiana",
    "name": "French Guiana",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#0055A4",
        "feature_primary": "#EF4135",
        "feature_secondary": "#9E2B23",
        "feature_minor": "#773E42",
        "feature_headwater": "#C98982",
        "text_primary": "#111827",
        "text_secondary": "#0055A4"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#EF4135",
        "feature_primary": "#0055A4",
        "feature_secondary": "#578FC3",
        "feature_minor": "#7298BE",
        "feature_headwater": "#35567A",
        "text_primary": "#F8FAFC",
        "text_secondary": "#EF4135"
      }
    }
  },
  {
    "id": "germany",
    "name": "Germany",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#DD0000",
        "feature_primary": "#BF9A00",
        "feature_secondary": "#A88800",
        "feature_minor": "#7C712F",
        "feature_headwater": "#CEBC6F",
        "text_primary": "#111827",
        "text_secondary": "#DD0000"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FFCE00",
        "feature_primary": "#DD0000",
        "feature_secondary": "#E95757",
        "feature_minor": "#C37983",
        "feature_headwater": "#85373E",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FFCE00"
      }
    }
  },
  {
    "id": "grenada",
    "name": "Grenada",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#CE1126",
        "feature_primary": "#007A5E",
        "feature_secondary": "#CAA712",
        "feature_minor": "#8F8239",
        "feature_headwater": "#E1CD79",
        "text_primary": "#111827",
        "text_secondary": "#CE1126"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FCD116",
        "feature_primary": "#007A5E",
        "feature_secondary": "#CE1126",
        "feature_minor": "#B45368",
        "feature_headwater": "#761123",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FCD116"
      }
    }
  },
  {
    "id": "guatemala",
    "name": "Guatemala",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#4997D0",
        "feature_primary": "#AE960F",
        "feature_secondary": "#A48D0F",
        "feature_minor": "#7A7438",
        "feature_headwater": "#CCBE77",
        "text_primary": "#111827",
        "text_secondary": "#3A79A6"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#F9D616",
        "feature_primary": "#4997D0",
        "feature_secondary": "#87BAE0",
        "feature_minor": "#8DB0CE",
        "feature_headwater": "#4F6E8A",
        "text_primary": "#F8FAFC",
        "text_secondary": "#F9D616"
      }
    }
  },
  {
    "id": "guyana",
    "name": "Guyana",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#CE1126",
        "feature_primary": "#FCD116",
        "feature_secondary": "#009E49",
        "feature_minor": "#000000",
        "feature_headwater": "#4A4A4A",
        "text_primary": "#000000",
        "text_secondary": "#009E49"
      },
      "dark": {
        "background": "#111111",
        "feature_major": "#CE1126",
        "feature_primary": "#FCD116",
        "feature_secondary": "#009E49",
        "feature_minor": "#FDFBF7",
        "feature_headwater": "#AAAAAA",
        "text_primary": "#FDFBF7",
        "text_secondary": "#FCD116"
      }
    }
  },
  {
    "id": "haiti",
    "name": "Haiti",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#00209F",
        "feature_primary": "#D21034",
        "feature_secondary": "#8B0B22",
        "feature_minor": "#6C2C42",
        "feature_headwater": "#BE7782",
        "text_primary": "#111827",
        "text_secondary": "#00209F"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#D21034",
        "feature_primary": "#334DB2",
        "feature_secondary": "#576CC0",
        "feature_minor": "#7285BC",
        "feature_headwater": "#354378",
        "text_primary": "#F8FAFC",
        "text_secondary": "#DD4C67"
      }
    }
  },
  {
    "id": "honduras",
    "name": "Honduras",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#0096B6",
        "feature_primary": "#008BA9",
        "feature_secondary": "#005C70",
        "feature_minor": "#20596D",
        "feature_headwater": "#72A4AD",
        "text_primary": "#111827",
        "text_secondary": "#007892"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#00BCE4",
        "feature_primary": "#42CDEB",
        "feature_secondary": "#82DEF2",
        "feature_minor": "#8AC3D8",
        "feature_headwater": "#4C8194",
        "text_primary": "#F8FAFC",
        "text_secondary": "#00BCE4"
      }
    }
  },
  {
    "id": "india",
    "name": "India",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#000080",
        "feature_primary": "#138808",
        "feature_secondary": "#FF9933",
        "feature_minor": "#AC7A4B",
        "feature_headwater": "#FEC58B",
        "text_primary": "#111827",
        "text_secondary": "#000080"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FF9933",
        "feature_primary": "#138808",
        "feature_secondary": "#4040A0",
        "feature_minor": "#666DAB",
        "feature_headwater": "#282A66",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FF9933"
      }
    }
  },
  {
    "id": "indonesia",
    "name": "Indonesia",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#FF0000",
        "feature_primary": "#BD0000",
        "feature_secondary": "#7D0000",
        "feature_minor": "#65262F",
        "feature_headwater": "#B7716F",
        "text_primary": "#111827",
        "text_secondary": "#E60000"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FF0000",
        "feature_primary": "#FF4242",
        "feature_secondary": "#FF8282",
        "feature_minor": "#CF919A",
        "feature_headwater": "#914F56",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FF0000"
      }
    }
  },
  {
    "id": "italy",
    "name": "Italy",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#CE2B37",
        "feature_primary": "#009246",
        "feature_secondary": "#00602E",
        "feature_minor": "#205B49",
        "feature_headwater": "#72A688",
        "text_primary": "#111827",
        "text_secondary": "#CE2B37"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#009246",
        "feature_primary": "#CE2B37",
        "feature_secondary": "#DF737B",
        "feature_minor": "#BD8996",
        "feature_headwater": "#804652",
        "text_primary": "#F8FAFC",
        "text_secondary": "#009246"
      }
    }
  },
  {
    "id": "jamaica",
    "name": "Jamaica",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#009B3A",
        "feature_primary": "#BE9D00",
        "feature_secondary": "#A88A00",
        "feature_minor": "#7C722F",
        "feature_headwater": "#CEBD6F",
        "text_primary": "#111827",
        "text_secondary": "#008431"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FED100",
        "feature_primary": "#009B3A",
        "feature_secondary": "#57BD7D",
        "feature_minor": "#72B198",
        "feature_headwater": "#356F53",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FED100"
      }
    }
  },
  {
    "id": "japan",
    "name": "Japan",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#BC002D",
        "feature_primary": "#8B0021",
        "feature_secondary": "#5C0016",
        "feature_minor": "#53263B",
        "feature_headwater": "#A4717B",
        "text_primary": "#111827",
        "text_secondary": "#BC002D"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#BF0D38",
        "feature_primary": "#CD4264",
        "feature_secondary": "#DE8299",
        "feature_minor": "#BD91A7",
        "feature_headwater": "#7F4F63",
        "text_primary": "#F8FAFC",
        "text_secondary": "#D25674"
      }
    }
  },
  {
    "id": "mexico",
    "name": "Mexico",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#006847",
        "feature_primary": "#CE1126",
        "feature_secondary": "#880B19",
        "feature_minor": "#6B2C3D",
        "feature_headwater": "#BD777D",
        "text_primary": "#111827",
        "text_secondary": "#006847"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#CE1126",
        "feature_primary": "#006847",
        "feature_secondary": "#579B86",
        "feature_minor": "#729F9C",
        "feature_headwater": "#355C58",
        "text_primary": "#F8FAFC",
        "text_secondary": "#DA4C5C"
      }
    }
  },
  {
    "id": "nicaragua",
    "name": "Nicaragua",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#0067C6",
        "feature_primary": "#004C93",
        "feature_secondary": "#003261",
        "feature_minor": "#204265",
        "feature_headwater": "#728CA4",
        "text_primary": "#111827",
        "text_secondary": "#0067C6"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#0067C6",
        "feature_primary": "#428FD5",
        "feature_secondary": "#82B5E3",
        "feature_minor": "#8AADD0",
        "feature_headwater": "#4C6B8B",
        "text_primary": "#F8FAFC",
        "text_secondary": "#3385D1"
      }
    }
  },
  {
    "id": "panama",
    "name": "Panama",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#072357",
        "feature_primary": "#DA121A",
        "feature_secondary": "#900C11",
        "feature_minor": "#6F2D39",
        "feature_headwater": "#C17878",
        "text_primary": "#111827",
        "text_secondary": "#072357"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#DA121A",
        "feature_primary": "#455A81",
        "feature_secondary": "#5B6E90",
        "feature_minor": "#7586A2",
        "feature_headwater": "#37445E",
        "text_primary": "#F8FAFC",
        "text_secondary": "#E14148"
      }
    }
  },
  {
    "id": "paraguay",
    "name": "Paraguay",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#0038A8",
        "feature_primary": "#D52B1E",
        "feature_secondary": "#8D1C14",
        "feature_minor": "#6E363A",
        "feature_headwater": "#BF807A",
        "text_primary": "#111827",
        "text_secondary": "#0038A8"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#D52B1E",
        "feature_primary": "#2656B5",
        "feature_secondary": "#577CC6",
        "feature_minor": "#728EC0",
        "feature_headwater": "#354B7B",
        "text_primary": "#F8FAFC",
        "text_secondary": "#DB4B40"
      }
    }
  },
  {
    "id": "russia",
    "name": "Russia",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#0039A6",
        "feature_primary": "#D52B1E",
        "feature_secondary": "#8D1C14",
        "feature_minor": "#6E363A",
        "feature_headwater": "#BF807A",
        "text_primary": "#111827",
        "text_secondary": "#0039A6"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#D52B1E",
        "feature_primary": "#2657B3",
        "feature_secondary": "#577CC4",
        "feature_minor": "#728EBF",
        "feature_headwater": "#354B7A",
        "text_primary": "#F8FAFC",
        "text_secondary": "#DB4B40"
      }
    }
  },
  {
    "id": "saint-kitts-and-nevis",
    "name": "Saint Kitts and Nevis",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#CE1126",
        "feature_primary": "#009E49",
        "feature_secondary": "#CAA712",
        "feature_minor": "#8F8239",
        "feature_headwater": "#E1CD79",
        "text_primary": "#111827",
        "text_secondary": "#CE1126"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FCD116",
        "feature_primary": "#009E49",
        "feature_secondary": "#CE1126",
        "feature_minor": "#B45368",
        "feature_headwater": "#761123",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FCD116"
      }
    }
  },
  {
    "id": "saint-lucia",
    "name": "Saint Lucia",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#4C9BBF",
        "feature_primary": "#BD9D10",
        "feature_secondary": "#A68A0F",
        "feature_minor": "#7B7238",
        "feature_headwater": "#CDBD77",
        "text_primary": "#111827",
        "text_secondary": "#39748F"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FCD116",
        "feature_primary": "#65CFFF",
        "feature_secondary": "#99DFFF",
        "feature_minor": "#97C4DF",
        "feature_headwater": "#59829B",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FCD116"
      }
    }
  },
  {
    "id": "saint-vincent-and-the-grenadines",
    "name": "Saint Vincent and the Grenadines",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#0072C6",
        "feature_primary": "#009E60",
        "feature_secondary": "#CAA712",
        "feature_minor": "#8F8239",
        "feature_headwater": "#E1CD79",
        "text_primary": "#111827",
        "text_secondary": "#0072C6"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FCD116",
        "feature_primary": "#009E60",
        "feature_secondary": "#0072C6",
        "feature_minor": "#4388C0",
        "feature_headwater": "#05467B",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FCD116"
      }
    }
  },
  {
    "id": "saudi-arabia",
    "name": "Saudi Arabia",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#006C35",
        "feature_primary": "#005027",
        "feature_secondary": "#00351A",
        "feature_minor": "#20433E",
        "feature_headwater": "#728E7D",
        "text_primary": "#111827",
        "text_secondary": "#006C35"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#0D733F",
        "feature_primary": "#42926A",
        "feature_secondary": "#82B79D",
        "feature_minor": "#8AAEA9",
        "feature_headwater": "#4C6C65",
        "text_primary": "#F8FAFC",
        "text_secondary": "#3D8F65"
      }
    }
  },
  {
    "id": "south-africa",
    "name": "South Africa",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#002395",
        "feature_primary": "#007749",
        "feature_secondary": "#DE3831",
        "feature_minor": "#9A454A",
        "feature_headwater": "#EC908A",
        "text_primary": "#111827",
        "text_secondary": "#002395"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FFB81C",
        "feature_primary": "#DE3831",
        "feature_secondary": "#007749",
        "feature_minor": "#438B7B",
        "feature_headwater": "#054937",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FFB81C"
      }
    }
  },
  {
    "id": "south-korea",
    "name": "South Korea",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#0047A0",
        "feature_primary": "#CD2E3A",
        "feature_secondary": "#871E26",
        "feature_minor": "#6A3744",
        "feature_headwater": "#BC8184",
        "text_primary": "#111827",
        "text_secondary": "#0047A0"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#CD2E3A",
        "feature_primary": "#1A59AA",
        "feature_secondary": "#5786C0",
        "feature_minor": "#7293BC",
        "feature_headwater": "#355178",
        "text_primary": "#F8FAFC",
        "text_secondary": "#D44D58"
      }
    }
  },
  {
    "id": "suriname",
    "name": "Suriname",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#B40A2D",
        "feature_primary": "#377E3F",
        "feature_secondary": "#C9AA19",
        "feature_minor": "#8E843D",
        "feature_headwater": "#E0CE7D",
        "text_primary": "#111827",
        "text_secondary": "#B40A2D"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#ECC81D",
        "feature_primary": "#377E3F",
        "feature_secondary": "#B40A2D",
        "feature_minor": "#A64F6C",
        "feature_headwater": "#680D27",
        "text_primary": "#F8FAFC",
        "text_secondary": "#ECC81D"
      }
    }
  },
  {
    "id": "trinidad-and-tobago",
    "name": "Trinidad and Tobago",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#CE1126",
        "feature_primary": "#980D1C",
        "feature_secondary": "#640912",
        "feature_minor": "#572B39",
        "feature_headwater": "#A97679",
        "text_primary": "#111827",
        "text_secondary": "#CE1126"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#CE1126",
        "feature_primary": "#DB4F5E",
        "feature_secondary": "#E78B95",
        "feature_minor": "#C296A5",
        "feature_headwater": "#845460",
        "text_primary": "#F8FAFC",
        "text_secondary": "#DA4C5C"
      }
    }
  },
  {
    "id": "turkiye",
    "name": "Türkiye",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#E30A17",
        "feature_primary": "#A80711",
        "feature_secondary": "#6F050B",
        "feature_minor": "#5D2935",
        "feature_headwater": "#AF7475",
        "text_primary": "#111827",
        "text_secondary": "#E30A17"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#E30A17",
        "feature_primary": "#EA4A53",
        "feature_secondary": "#F1888D",
        "feature_minor": "#C794A0",
        "feature_headwater": "#8A525C",
        "text_primary": "#F8FAFC",
        "text_secondary": "#E93B45"
      }
    }
  },
  {
    "id": "united-kingdom",
    "name": "United Kingdom",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#012169",
        "feature_primary": "#C8102E",
        "feature_secondary": "#840B1E",
        "feature_minor": "#692C40",
        "feature_headwater": "#BA7780",
        "text_primary": "#111827",
        "text_secondary": "#012169"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#C8102E",
        "feature_primary": "#40588E",
        "feature_secondary": "#576C9C",
        "feature_minor": "#7285A9",
        "feature_headwater": "#354364",
        "text_primary": "#F8FAFC",
        "text_secondary": "#D64C62"
      }
    }
  },
  {
    "id": "uruguay",
    "name": "Uruguay",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#0038A8",
        "feature_primary": "#BD9D10",
        "feature_secondary": "#A68A0F",
        "feature_minor": "#7B7238",
        "feature_headwater": "#CDBD77",
        "text_primary": "#111827",
        "text_secondary": "#0038A8"
      },
      "dark": {
        "background": "#0B1020",
        "feature_major": "#FCD116",
        "feature_primary": "#2656B5",
        "feature_secondary": "#577CC6",
        "feature_minor": "#728EC0",
        "feature_headwater": "#354B7B",
        "text_primary": "#F8FAFC",
        "text_secondary": "#FCD116"
      }
    }
  },
  {
    "id": "usa",
    "name": "United States",
    "variants": {
      "light": {
        "background": "#FDFBF7",
        "feature_major": "#B31942",
        "feature_primary": "#0A3161",
        "feature_secondary": "#3B82F6",
        "feature_minor": "#000000",
        "feature_headwater": "#4A4A4A",
        "text_primary": "#000000",
        "text_secondary": "#0A3161"
      },
      "dark": {
        "background": "#0A3161",
        "feature_major": "#B31942",
        "feature_primary": "#FFFFFF",
        "feature_secondary": "#60A5FA",
        "feature_minor": "#94A3B8",
        "feature_headwater": "#334155",
        "text_primary": "#FFFFFF",
        "text_secondary": "#B31942"
      }
    }
  }
]
        $flag_presets$::jsonb
    )
)
INSERT INTO public.platform_rules (
    id,
    rule_type,
    version,
    payload,
    is_active
)
SELECT
    'flag:' || (payload ->> 'id'),
    'flag',
    1,
    payload,
    TRUE
FROM desired_flags
ON CONFLICT (id) DO UPDATE
SET
    rule_type = EXCLUDED.rule_type,
    version = EXCLUDED.version,
    payload = EXCLUDED.payload,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE
    public.platform_rules.rule_type IS DISTINCT FROM EXCLUDED.rule_type
    OR public.platform_rules.version IS DISTINCT FROM EXCLUDED.version
    OR public.platform_rules.payload IS DISTINCT FROM EXCLUDED.payload
    OR public.platform_rules.is_active IS DISTINCT FROM TRUE;
