import { ArchitectureDiagram, DocPage, DocSection, Note, StackTable, Status } from "../components";

export default function HpsPortalDocumentation() {
  return <DocPage system="HPS Portal" eyebrow="System documentation · platform shell" title="HPS Portal" summary="The branded access and discovery layer that houses HPS Geospatial products, documentation, project context, and links into operational tools such as Drone Zoning and the Poster Generator.">
    <DocSection number="01" title="System purpose"><div className="doc-grid"><article className="doc-card"><h3>One front door</h3><p>Give partners and internal users a clear, trusted place to discover HPS products, pilots, documentation, and contact paths.</p></article><article className="doc-card"><h3>Product hierarchy</h3><p>Make HPS Geospatial the parent identity while keeping Drone Zoning and Poster Generator visually distinct product surfaces.</p></article><article className="doc-card"><h3>Navigation layer</h3><p>Route users to the right system without duplicating operational workflows that belong inside each product.</p></article></div></DocSection>
    <DocSection number="02" title="Proposed architecture"><ArchitectureDiagram nodes={[{label:"Visitor",detail:"Public or signed-in user",tone:""},{label:"HPS Portal",detail:"Brand · navigation · content",tone:""},{label:"Product routes",detail:"Drone · Poster · Docs",tone:""},{label:"Shared services",detail:"Identity · analytics · assets",tone:"data"}]} caption="The Portal is a discovery and access layer; product-specific data and workflows remain owned by the systems they describe." /><Note>The current application repository exposes workspace authentication helpers and optional Cloudflare bindings. Whether the Portal should share identity, navigation, or only visual language is an architectural decision to confirm.</Note></DocSection>
    <DocSection number="03" title="Stack to confirm"><StackTable rows={[["Web shell", "To confirm", "Portal landing, navigation, and content routes"],["Content", "To confirm", "Product descriptions, documentation, announcements, and downloads"],["Identity", "Workspace auth headers available", "Optional sign-in and role-aware links"],["Assets", "HPS design system", "Logos, product marks, screenshots, and editorial imagery"],["Integrations", "To confirm", "Links or embedded views into Drone Platform and Poster Generator"]]} /></DocSection>
    <DocSection number="04" title="Portal responsibilities"><div className="doc-grid"><article className="doc-card"><h3>Discover</h3><p>Explain what each HPS product does and who it serves.</p></article><article className="doc-card"><h3>Orient</h3><p>Provide system documentation, methodology, status, and ownership context.</p></article><article className="doc-card"><h3>Connect</h3><p>Offer access links, contact actions, downloads, and pathways into applications.</p></article></div></DocSection>
    <DocSection number="05" title="Status and decisions"><div className="doc-grid"><article className="doc-card"><Status>Implemented</Status><h3>Brand foundation</h3><p>HPS Geospatial logo assets and parent/product hierarchy are available for the Portal surface.</p></article><article className="doc-card"><Status tone="decision">To confirm</Status><h3>Canonical Portal repository</h3><p>Identify the Portal codebase and deployment target so this documentation can be connected to the actual site.</p></article><article className="doc-card"><Status tone="planned">Planned</Status><h3>Shared navigation</h3><p>Define the durable links, permissions, and cross-product navigation model.</p></article></div></DocSection>
  </DocPage>;
}
