import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..', '..');

const LEDGER_JSON_PATH = path.join(PROJECT_ROOT, '.agent', 'state', 'command-ledger.json');
const LEDGER_MD_PATH = path.join(PROJECT_ROOT, 'docs', 'workflow', 'reports', 'command-ledger.md');

/**
 * Standardized logging utility for pipeline governance.
 * Appends an entry to both the machine-readable JSON ledger
 * and the human-readable Markdown ledger.
 *
 * @param {Object} entry - The ledger entry. Must include at minimum:
 *   phase, subphase, executor, commands, mutations.
 */
export function logToLedger(entry) {
  try {
    // Ensure the state directory exists
    const stateDir = path.dirname(LEDGER_JSON_PATH);
    if (!fs.existsSync(stateDir)) {
      fs.mkdirSync(stateDir, { recursive: true });
    }

    // Read or initialize the JSON ledger
    let ledger = {
      version: '1.0.0',
      project: 'hydrographic-poster-generator',
      phase: '1.0',
      history: [],
    };
    if (fs.existsSync(LEDGER_JSON_PATH)) {
      ledger = JSON.parse(fs.readFileSync(LEDGER_JSON_PATH, 'utf8'));
    }

    // Build the new entry with auto-generated timestamp
    const newEntry = {
      timestamp: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      ...entry,
    };

    ledger.history.push(newEntry);

    // Write JSON ledger
    fs.writeFileSync(LEDGER_JSON_PATH, JSON.stringify(ledger, null, 2));
    console.log(`📓 Command logged to ledger: ${entry.subphase}`);

    // Regenerate the human-readable Markdown ledger
    regenerateMarkdownLedger(ledger);
  } catch (err) {
    console.error('⚠️ Failed to write to command ledger:', err.message);
  }
}

/**
 * Regenerates the human-readable Markdown ledger from the full JSON ledger.
 * @param {Object} ledger - The full parsed ledger object.
 */
function regenerateMarkdownLedger(ledger) {
  const mdDir = path.dirname(LEDGER_MD_PATH);
  if (!fs.existsSync(mdDir)) {
    fs.mkdirSync(mdDir, { recursive: true });
  }

  const header = [
    '# Command Ledger',
    '',
    '> Auto-generated human-readable mirror of `.agent/state/command-ledger.json`.',
    '> Do not edit this file manually. It is regenerated by `scripts/utils/ledger.mjs`.',
    '',
    '| Phase | Subphase | Timestamp | Executor | Commands Used | Mutations | Status | Notes |',
    '| :---- | :------- | :-------- | :------- | :------------ | :-------- | :----- | :---- |',
  ];

  const rows = ledger.history.map((e) => {
    const commandsUsed = Array.isArray(e.commandsUsed)
      ? e.commandsUsed.join(', ')
      : Array.isArray(e.commands)
        ? e.commands.map((c) => c.cmd).join(', ')
        : '—';
    const mutations = Array.isArray(e.mutations) ? e.mutations.join(', ') : '—';
    const status = e.status || '—';
    const notes = e.notes || '—';
    const ts = e.timestamp ? e.timestamp.substring(0, 19) : '—';

    return `| ${e.phase || '—'} | ${e.subphase || '—'} | ${ts} | ${e.executor || '—'} | ${commandsUsed} | ${mutations} | ${status} | ${notes} |`;
  });

  const content = [...header, ...rows, ''].join('\n');
  fs.writeFileSync(LEDGER_MD_PATH, content);
  console.log('📄 Markdown ledger regenerated.');
}
