import { ArchitectureDiagram, DocPage, DocSection, Note, Status } from "../components";

export default function EcosystemDocumentation() {
  return <DocPage system="HPS Portal ecosystem" eyebrow="System documentation · cross-product view" title="HPS Portal Ecosystem" summary="A shared architecture view for the HPS Geospatial product family: the Portal provides orientation and access, while Drone Zoning and Poster Generator own their specialized workflows.">
    <DocSection number="01" title="Ecosystem model"><ArchitectureDiagram nodes={[{label:"HPS Geospatial",detail:"Parent identity · standards",tone:""},{label:"HPS Portal",detail:"Discovery · documentation · access",tone:""},{label:"Drone Platform",detail:"Spatial analysis · classification",tone:"data"},{label:"Poster Generator",detail:"Composition · visual outputs",tone:"data"},{label:"Shared services",detail:"Identity · assets · observability",tone:"future"}]} caption="The ecosystem is intentionally modular: shared brand and platform services connect the products without collapsing their responsibilities." /></DocSection>
    <DocSection number="02" title="How the systems relate"><div className="doc-grid"><article className="doc-card"><h3>Portal → products</h3><p>The Portal directs users into the right operational surface and provides shared context, documentation, and contact paths.</p></article><article className="doc-card"><h3>Drone → Poster</h3><p>Approved Drone Platform maps or analysis outputs may become source material for a designed poster or briefing artifact.</p></article><article className="doc-card"><h3>Products → Portal</h3><p>Products can publish status, documentation, outputs, or links back to the Portal without surrendering their core workflows.</p></article></div><Note tone="important">The ecosystem should share identity, brand tokens, and link conventions first. Data sharing and shared persistence should be introduced only where ownership and governance are explicit.</Note></DocSection>
    <DocSection number="03" title="Cross-system principles"><ol className="doc-grid"><li className="doc-card"><h3>Clear ownership</h3><p>Each system owns its domain data, workflows, and implementation decisions.</p></li><li className="doc-card"><h3>Explainable handoffs</h3><p>When one system consumes another system’s output, preserve source, version, attribution, and status metadata.</p></li><li className="doc-card"><h3>Shared design language</h3><p>Use HPS Geospatial tokens and logo rules while maintaining distinct product identities.</p></li><li className="doc-card"><h3>Implemented vs proposed</h3><p>Label planned exports, integrations, and services until they are verified in production code.</p></li></ol></DocSection>
    <DocSection number="04" title="Shared stack candidates"><div className="doc-grid"><article className="doc-card"><Status>Available</Status><h3>HPS design system</h3><p>Corporate logo assets, color tokens, typography guidance, and product-brand rules.</p></article><article className="doc-card"><Status tone="decision">To confirm</Status><h3>Identity and access</h3><p>Decide whether products share workspace identity, a central portal account, or independent access controls.</p></article><article className="doc-card"><Status tone="planned">Planned</Status><h3>Artifact exchange</h3><p>Define a durable contract for maps, posters, metadata, downloads, and versioned outputs.</p></article></div></DocSection>
    <DocSection number="05" title="Next architecture decisions"><ul><li>Confirm the canonical repository and deployment target for each system.</li><li>Inventory which services are truly shared versus product-specific.</li><li>Define identity, permissions, and public/private boundaries.</li><li>Specify the metadata contract for Drone Platform outputs consumed by Poster Generator.</li><li>Choose whether documentation is authored in code, a CMS, or a repository-backed content workflow.</li></ul></DocSection>
  </DocPage>;
}
