import { ArchitectureDiagram, DocPage, DocSection, Note, StackTable, Status } from "../components";

export default function DronePlatformDocumentation() {
  return <DocPage system="Drone Platform" eyebrow="System documentation · current pilot" title="Drone Zoning Platform" summary="A map-integrated decision-support platform for evaluating drone operating suitability, explaining the factors behind each result, and publishing analysis-ready spatial outputs.">
    <DocSection number="01" title="System purpose"><div className="doc-grid"><article className="doc-card"><h3>What it does</h3><p>Combines spatial datasets, regulatory constraints, infrastructure, settlements, and policy priorities into a configurable suitability analysis.</p></article><article className="doc-card"><h3>Who it serves</h3><p>Government agencies, regional councils, civil aviation and public-safety authorities, infrastructure operators, consultants, and commercial drone operators.</p></article><article className="doc-card"><h3>Current boundary</h3><p>The current application is a web-based prototype focused on the Region 4 pilot and the published-run review experience.</p></article></div><Note>PDF, GeoJSON, CSV, and Shapefile exports are represented in the product direction, but should be treated as planned until the corresponding generation and download paths are implemented.</Note></DocSection>
    <DocSection number="02" title="Architecture at a glance"><ArchitectureDiagram nodes={[{label:"Browser",detail:"React UI · map review",tone:""},{label:"Vinext app",detail:"Next-style routes · TypeScript",tone:""},{label:"Cloudflare Worker",detail:"Edge request and asset handling",tone:""},{label:"D1 / Drizzle",detail:"Optional metadata persistence",tone:"data"},{label:"Object storage",detail:"Future layer artifacts",tone:"future"}]} caption="Current application shape with optional persistence and future spatial-artifact storage shown separately from the core request path." /><Note tone="important">The current repository includes the Cloudflare/Vinext worker and optional D1/Drizzle shape. The schema is intentionally empty today; database-backed run records, permissions, and layer artifacts remain implementation decisions.</Note></DocSection>
    <DocSection number="03" title="Software stack"><StackTable rows={[["UI", "React 19 + TypeScript", "Composable page and dashboard interfaces"],["Application", "Next-style App Router via vinext", "Route rendering and application structure"],["Build", "Vite + Cloudflare vinext plugin", "Worker-compatible build output"],["Runtime", "Cloudflare Workers", "Request handling and edge deployment target"],["Persistence", "Cloudflare D1 + Drizzle ORM", "Optional relational metadata layer; schema currently empty"],["Assets", "Cloudflare Assets / image optimization", "Static assets and image handling"]]} /></DocSection>
    <DocSection number="04" title="Primary data flow"><ol className="doc-grid"><li className="doc-card"><h3>1. Configure</h3><p>Authorized users define factors, weights, buffers, thresholds, and policy settings.</p></li><li className="doc-card"><h3>2. Analyze</h3><p>The analysis engine evaluates spatial cells against source datasets and configured rules.</p></li><li className="doc-card"><h3>3. Classify</h3><p>Each location receives a suitability class, score, and supporting factors for review.</p></li><li className="doc-card"><h3>4. Publish</h3><p>An approved run becomes the public or operational map view for downstream users.</p></li><li className="doc-card"><h3>5. Inspect</h3><p>Users select cells to understand constraints, score, confidence, and policy context.</p></li><li className="doc-card"><h3>6. Export</h3><p>Document and GIS export workflows can package the run for reports and sharing.</p></li></ol></DocSection>
    <DocSection number="05" title="Implementation status"><div className="doc-grid"><article className="doc-card"><Status>Implemented</Status><h3>Overview route</h3><p>Responsive executive overview, HPS branding, product links, print styles, and supplied application preview.</p></article><article className="doc-card"><Status>Implemented</Status><h3>Prototype console</h3><p>Published-run dashboard surface with map preview, metrics, selected-cell detail, workflow, and run-history examples.</p></article><article className="doc-card"><Status tone="planned">Planned</Status><h3>Production data services</h3><p>Persistent model runs, authoritative spatial ingestion, user roles, analysis execution, and export services.</p></article></div></DocSection>
    <DocSection number="06" title="Related surfaces"><div className="doc-links"><a href="/executive-overview">Executive overview</a><a href="/documentation/ecosystem">View ecosystem architecture</a><a href="/">Open planning console</a></div></DocSection>
  </DocPage>;
}
