import { ArchitectureDiagram, DocPage, DocSection, Note, StackTable, Status } from "../components";

export default function PosterGeneratorDocumentation() {
  return <DocPage system="Poster Generator" eyebrow="System documentation · product surface" title="Hydrographic Poster Generator" summary="A companion product for transforming hydrographic or spatial source material into designed, shareable poster outputs. This page separates the product concept from the production stack still to be confirmed.">
    <DocSection number="01" title="System purpose"><div className="doc-grid"><article className="doc-card"><h3>What it does</h3><p>Turns hydrographic or mapped source data into a visual poster composition with configurable layout, branding, labels, and export settings.</p></article><article className="doc-card"><h3>Why it matters</h3><p>Provides a communication surface for technical spatial information that is easier to present, print, and share with non-specialist audiences.</p></article><article className="doc-card"><h3>Relationship to Drone Zoning</h3><p>Poster generation can consume approved maps, classifications, or exported layers from the Drone Platform without becoming part of its analysis engine.</p></article></div><Note>Exact runtime, rendering pipeline, storage model, and supported input formats should be confirmed against the poster-generator repository before this document is treated as an implementation specification.</Note></DocSection>
    <DocSection number="02" title="Proposed architecture"><ArchitectureDiagram nodes={[{label:"Source data",detail:"Raster · vector · analysis layer",tone:"data"},{label:"Poster editor",detail:"Composition · labels · theme",tone:""},{label:"Render service",detail:"Preview · rasterize · paginate",tone:""},{label:"Export bundle",detail:"PNG · PDF · print package",tone:"future"}]} caption="Working architecture for the poster workflow; the render and export services are shown as proposed until verified in the application source." /><Note tone="important">Keep poster composition downstream of analysis. The Poster Generator should read approved or user-supplied data and should not silently alter the analytical classification that produced a map.</Note></DocSection>
    <DocSection number="03" title="Stack to confirm"><StackTable rows={[["Editor UI", "To confirm", "Poster composition, controls, and preview"],["Rendering", "To confirm", "High-resolution preview and final output generation"],["Data inputs", "To confirm", "Raster, vector, image, or platform-exported layer support"],["Storage", "To confirm", "Projects, assets, templates, and generated outputs"],["Delivery", "To confirm", "Browser download, share link, or portal publishing"]]} /></DocSection>
    <DocSection number="04" title="Primary workflow"><ol className="doc-grid"><li className="doc-card"><h3>1. Select source</h3><p>Choose a map, hydrographic dataset, image, or approved Drone Platform output.</p></li><li className="doc-card"><h3>2. Compose</h3><p>Set poster size, layout, title, legend, labels, annotations, and brand treatment.</p></li><li className="doc-card"><h3>3. Preview</h3><p>Review readable hierarchy, scale, contrast, and print-safe spacing before export.</p></li><li className="doc-card"><h3>4. Generate</h3><p>Render a high-resolution poster and package the output with source and attribution metadata.</p></li></ol></DocSection>
    <DocSection number="05" title="Status and decisions"><div className="doc-grid"><article className="doc-card"><Status tone="decision">To confirm</Status><h3>Authoritative repository</h3><p>Confirm the canonical Poster Generator repository and whether it shares code or deployment resources with the Drone Platform.</p></article><article className="doc-card"><Status tone="planned">Planned</Status><h3>Template library</h3><p>Define reusable HPS poster templates, map treatments, legends, and print presets.</p></article><article className="doc-card"><Status tone="planned">Planned</Status><h3>Portal handoff</h3><p>Decide whether generated posters are downloaded directly or published into the HPS Portal as managed artifacts.</p></article></div></DocSection>
  </DocPage>;
}
