#!/usr/bin/env python3
"""Generate or verify migration 016 from the canonical Python flag catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
MIGRATION_PATH = ROOT / "db" / "migrations" / "016_seed_flag_presets.sql"
sys.path.insert(0, str(BACKEND))

from app.config.flag_presets import FLAG_PRESETS  # noqa: E402


def render_migration() -> str:
    payloads = [
        FLAG_PRESETS[preset_id]
        for preset_id in sorted(FLAG_PRESETS)
    ]
    catalog_json = json.dumps(payloads, ensure_ascii=False, indent=2)
    return f"""-- 016_seed_flag_presets.sql
-- Generated by scripts/generate_flag_preset_migration.py.
-- Seeds the canonical 45-country flag palette catalog without overwriting
-- created_at or touching unrelated/custom rule rows.

WITH desired_flags AS (
    SELECT value AS payload
    FROM jsonb_array_elements(
        $flag_presets$
{catalog_json}
        $flag_presets$::jsonb
    )
)
INSERT INTO public.platform_rules (
    id,
    rule_type,
    version,
    payload,
    is_active
)
SELECT
    'flag:' || (payload ->> 'id'),
    'flag',
    1,
    payload,
    TRUE
FROM desired_flags
ON CONFLICT (id) DO UPDATE
SET
    rule_type = EXCLUDED.rule_type,
    version = EXCLUDED.version,
    payload = EXCLUDED.payload,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE
    public.platform_rules.rule_type IS DISTINCT FROM EXCLUDED.rule_type
    OR public.platform_rules.version IS DISTINCT FROM EXCLUDED.version
    OR public.platform_rules.payload IS DISTINCT FROM EXCLUDED.payload
    OR public.platform_rules.is_active IS DISTINCT FROM TRUE;
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when migration 016 differs from the canonical catalog.",
    )
    args = parser.parse_args()
    expected = render_migration()

    if args.check:
        actual = MIGRATION_PATH.read_text(encoding="utf-8") if MIGRATION_PATH.exists() else ""
        if actual != expected:
            print(
                f"{MIGRATION_PATH.relative_to(ROOT)} is stale; "
                "run scripts/generate_flag_preset_migration.py",
                file=sys.stderr,
            )
            return 1
        print(f"{MIGRATION_PATH.relative_to(ROOT)} matches {len(FLAG_PRESETS)} presets")
        return 0

    MIGRATION_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {MIGRATION_PATH.relative_to(ROOT)} with {len(FLAG_PRESETS)} presets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
